name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          cd client
          VITE_APP_API=https://api.greenbackclaims.com/ npm run build
          ls

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to EC2
        run: |
    
          sshpass -p "12345" scp -o StrictHostKeyChecking=no -r client/dist/* ec2-user@18.204.42.116:/var/www/html
          echo "Deployment completed successfully!"
